My first Microverse project
Yerimah/Hello-world pull request #1
Opened 2021-11-23 16:06 UTC by Yerimah

2021-11-23 18:51 UTC, andersonlebon requested changes
Hi @Yerimah 
Good job so far!
I know you have worked hard on making this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!
![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- Good work on implementing linters :heavy_check_mark: 

## Required Changes ♻️

- [ ] The Repository should have a descriptive Pull Request message and a Pull Request meaningful title, this is important because we let the reviewer or any other user the intent of the changes we are about to merge with a production branch.
- [ ]  Kindly Check the comments under the review._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-23 18:51 UTC, andersonlebon commented on README.md
> +This is my first project in microverse. In this project I am required to set up the following:
- [ ] Kindly follow this [template](https://github.com/microverseinc/readme-template) while building your README. 
- [ ] Kindly change the description of your project. This should be a short summary of what your project is supposed to do and not talk about you.

2021-11-23 18:51 UTC, andersonlebon commented on node_modules/.bin/autoprefixer
> +#!/bin/sh
- [ ] Kindly remove the `nodemodules` in your repository and put it in the `.gitignore` file. I know it will be difficult to remove the `nodemodules` but if you follow all the steps in this [article](https://medium.com/@buyananderson/accidentally-push-to-github-the-node-modules-without-ignoring-it-f766dad15eaa), the `nodemodules` will disappear.
:skull: The `nodemodules` directory should never appear in your Repository because this consumes a lot of space

2021-11-23 22:28 UTC, Yerimah commented on README.md
> +This is my first project in microverse. In this project I am required to set up the following:
I have made the changes. thank you.

2021-11-24 00:22 UTC, andersonlebon approved these changes
Hi @Yerimah  
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- You  are following GitHub actions :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is now professional :heavy_check_mark: 

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-11-24 00:22 UTC, andersonlebon commented on README.md
> +- LinkedIn: [LinkedIn](https://www.linkedin.com/in/daniel-yerimah/)
### [OPTIONAL]
- [ ] Instead of writing - LinkedIn: [LinkedIn]... you may use your `name` or your `Linkedin username` like - LinkedIn: [@Yerimah... ]..... This will give a simple idea to the visitor of which profile is visiting before is redirected there.

2021-11-24 06:46 UTC, merged